(defun solve (f min max epsilon)
  (let (i iv)
    (do ((x min (+ x epsilon)))
        ((> x max))
      (let ((xv (funcall f x)))
        (when (or (null i)
                  (< (abs xv) (abs iv)))
          (setf i x iv xv))))
     i))