(defun contest ()
  (let ((i 0) (o 0))
    (dotimes (j 10 (values i o))
      (if (zerop (random 2))
          (incf i)
          (incf o)))))

(defun check (n)
  (let ((ti 0) (to 0))
    (dotimes (j n)
      (multiple-value-bind (ci co) (contest)
        (incf ti ci)
        (incf to co)))
    (let ((s (+ ti to)))
      (values (float (/ ti s)) (float (/ to s))))))