(defun filter (fn lst)
  (let ((acc nil))
    (dolist (x lst)
      (let ((val (funcall fn x)))
        (if val (push val acc))))
    (nreverse acc)))

(defun our-remove-if (fn lst)
  (filter #'(lambda (x)
              (and (not (funcall fn x)) x))
          lst))